### PR TITLE
Refactor HomeScreen and fix pull to refresh

### LINKED ISSUE #9: Pull to refresh webview is buggy
The current pull to refresh implementation wraps the webview in a scroll view which has a few noticeable issues. 

* ~Scroll view steals focus on Android preventing scrolling up in webview.~ Pull to refresh has been removed for Android. 
* User must stop scrolling before attempting pulling to refresh on iOS. 

This [pull request](https://github.com/react-native-community/react-native-webview/pull/362) on `react-native-webview` will introduce this functionality to the webview. When it is available we should make use of this feature instead of the current implementation.

### PR DESCRIPTION
**Pull request by thornbill**
* Refactor HomeScreen into multiple components
* Moves logic for managing rotation lock state and hiding the status bar to App component
* Adds `action()` calls to functions that modify mobx state: https://mobx.js.org/refguide/action.html
* Adds `isFullscreen` to root mobx store
* Fixes buginess with pull to refresh (especially for Android)

This ended up being larger than expected and didn't even address the issue I started out looking at. :speak_no_evil: 

Fixes #9

### CODE REVIEW

File: constants/Colors.js [hunk 1]
```diff
@@ -5,19 +5,22 @@
  */
 const backgroundColor = '#101010';
 const textColor = '#fff';
-const tintColor = '#00a4dc';
+const jellyBlue = '#00a4dc';
+const jellyPurple = '#AA5CC3';
```
Comment (dkanada) [inline constants/Colors.js]: I like to avoid product names in the codebase to keep everything generic, just a preference.

Comment (thornbill) [reply constants/Colors.js]: Good point! They have been updated!

**Review by anthonylavado — APPROVED** [review]
